Repository atom-minimap/minimap, pull requests merged in 2020-11, with the labels that each got.

#710 Update Tests and CI
  .github/workflows/CI.yml
  .travis.yml
  ci/build-minimap.sh
  ci/build-package.sh
  package.json
  spec/minimap-element-spec.js
  spec/minimap-spec.js
Labels: ci, tests

#711 Update Tests and CI
  .github/workflows/CI.yml
  CHANGELOG.md
  package.json
  spec/minimap-element-spec.js
Labels: ci, tests

#712 fix: add activation hook
  .github/workflows/CI.yml
  CHANGELOG.md
  package.json
  spec/minimap-element-spec.js
  spec/minimap-main-spec.js
Labels: performance

#714 fix: bump dependencies
  lib/adapters/legacy-adapter.js
  lib/decoration.js
  lib/decorators/element.js
  lib/decorators/include.js
  lib/main.js
  lib/minimap-element.js
  lib/minimap-plugin-generator-element.js
  lib/minimap-quick-settings-element.js
  lib/minimap.js
  lib/mixins/canvas-drawer.js
  lib/mixins/decoration-management.js
  lib/mixins/dom-styles-reader.js
  lib/mixins/plugin-management.js
  package.json
  spec/canvas-layer-spec.js
  spec/helpers/events.js
  spec/helpers/workspace.js
  spec/minimap-element-spec.js
  spec/minimap-main-spec.js
  spec/minimap-spec.js
Labels: dependencies, performance

#716 feat: use optimal settings as the default
  lib/minimap-element.js
  package.json
  spec/minimap-element-spec.js
Labels: enhancement, performance

#713 fix: prevent error when minimap squashed
  lib/canvas-layer.js
Labels: bug

#718 feat: limit the number of tokens that are rendered for one line
  lib/mixins/canvas-drawer.js
  package.json
Labels: bug, performance

#721 feat: use desynchronized canvas
  lib/canvas-layer.js
Labels: performance

#720 feat: add css containment to minimap elements
  styles/minimap.less
Labels: performance

#719 feat: use requestAnimationFrame to scheduleChanges
  lib/minimap.js
  package.json
  spec/minimap-spec.js
Labels: performance

#684 Mark atom-utils event listeners as passive
  lib/minimap-element.js
  lib/minimap-quick-settings-element.js
Labels: performance

#726 fix: make scroll indicator more visible
  styles/minimap.less
Labels: enhancement
